config/routes.rb
NewApp::Application.routes.draw do

  resources :lists do
    resources :tasks
  end

  match 'lists/:list_id/tasks/:id/find_list' => 'tasks#find_list'

  
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  

  root :to => 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  
  validates :name, :presence => true
  validates :description, :presence => true
  has_many :tasks
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  
  belongs_to :list

  validates :description, :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates :username, :presence => true
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password ,:username , :password_confirmation
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  respond_to :html, :xml, :js

   #By default priority is 1.If user does not select priority from drop down box ,then it should be one.

  def index
    if user_signed_in?
      #@lists = List.find(:all,:order=>["priority ASC"],:conditions=>["user_id=?" ,current_user.id]);
      @lists = List.order("priority ASC").where("user_id=?", current_user.id);
      @bbb = @lists.count
      @user = User.find(:all, :conditions=>["id=?", current_user.id]);
      @user.each do |f|
        @ppp = f.username

      end

    end
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params[:list])
    if @list.save
      flash[:notice] = "List created."
      respond_with(@list, :location => list_url(@list))
    else
      flash[:error] = "Could not create list"
      redirect_to new_list_url
    end
  end

  def show
    @list = List.find(params[:id]);
    @task = @list.tasks.new
    @task1 = Task.order("priority ASC").where("list_id =?", params[:id]);
    @aaa= @task1.count

  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update_attributes(params[:list])
      flash[:notice] = "List updated."
      respond_with(@list, :location => list_url(@list))
    else
      flash[:error] = "Could not update list"
      redirect_to edit_list_path(@list)
    end
  end

  def destroy
    @list = List.find(params[:id])
    if @list.destroy
      flash[:notice] = "List deleted"
      redirect_to lists_url
    else
      flash[:error] = "Could not delete list?"
      redirect_to lists_url
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :find_list
  respond_to :html, :xml, :js

  def create

    @task = @list.tasks.new(params[:task])

    if @task.save
      flash[:notice] = "Item created successfully."
      redirect_to list_url(@list)
    else
      flash[:error] = "Item not created please enter description.."
      redirect_to list_url(@list)
    end
  end


  def find_list
    @list = List.find(params[:list_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Application</title>
   <div id="user_nav">
    <% if user_signed_in? %>

      <span> <%= link_to 'Logout', destroy_user_session_path ,:confirm => "Are you sure want to Logout?" ,:style => "margin-left:800px ! important;font-size: 14px;"%></span>

    <% else %>
        <%= link_to 'Register', new_user_registration_path , :style => "font-size: 14px;"%> or <%= link_to 'Login', new_user_session_path , :style => "font-size: 14px;"%>
    <% end %>
</div>

  <%= stylesheet_link_tag :all %>
 <%= javascript_include_tag :defaults %>
  <%#= javascript_include_tag '/javascripts/jquery-1.7.1.min.js' %>
<%= csrf_meta_tag %>
</head>
<body>

	<div id="flash">
	  <% flash.each do |key, value| -%>
	    <div id="flash_<%= key %>"><%=h value %></div>
	  <% end -%>
	</div>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
	
	<label>Name:
		<p><%= f.text_field :name ,:id=>"name" %></p>
	</label>
	 <%#= hidden_field_tag  :user_id , current_user.id %>
	<label>Description:
		<p><%= f.text_field :description,:id=>"description" %></p>
	</label>


	 <label>Priority:
    <%= select "list", "priority", ['1' ,'2' ,'3' ,'4' ,'5','6' ,'7' ,'8' ,'9' ,'10'], {:tabindex=>"3", :id=>'priority', :name=>"priority"} %>


	</label>
     <%= f.hidden_field :user_id, :value => current_user.id %>
	<p><%= f.submit "Create List" %></p>
	
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render :partial => 'form' %>

app/views/lists/index.html.erb
<% if user_signed_in? %>
     <h2>Welcome! <%= @ppp %> to My App  </h2>
    </br>
 <% if !@lists.nil?   %>
     <% if @bbb <= 1%>
            <% if @bbb == 0%>
            <h3>You do not have any list.Please create your list(s):</h3>
              <% else %>
             <h3>List:</h3>
           <% end %>
             <% else %>
             <h3>Lists:</h3>
            <% end %>

 </br></br>
 <% @lists.each do |list| %>

     <h3>Name:</h3><h4><%= link_to "#{list.name}", list_url(list) %></h4>
	 <h3>Description: </h3><%= list.description %> - <%= link_to "Edit", edit_list_url(list) %> | <%= link_to "Delete", list_url(list),:confirm => "Are you sure want to delete #{list.name}(list)?", :method => :delete %>
     <h3>Priority: </h3><%= list.priority %>
            </br>  </br> </br>
<% end %>

 <%end %>
     <%= link_to "Add new list", new_list_url %>
    <% else %>
        <h2>Welcome! Guest to My App </h2>

 <% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<h3>List:</h3>

</br>
<h3>Name:<%= @list.name %></h3>
<h3>Description:<%= @list.description %></h3>
<h3>Priority:<%= @list.priority %></h3>
<br>   <br> <br> <br>
<% if @aaa <= 1 %>
    <% if @aaa == 0 %>
        <h3>You do not have any item.Please create item(s).</h3>
    <% else %>
        <h3>Item:</h3>
    <% end %>
<% else %>
    <h3>Items:</h3>
<% end %>



<ul>
  <% if !@task1.nil? %>
      <% @task1.each do |task| %>

          <h4>Description: <%= task.description %></h4>
          <h4>Priority:<%= task.priority %></h4>
          </br>  </br>
      <% end %>
  <% end %>
</ul>


<%= form_for [@list, @task] do |f| %>

    <p><%= f.text_field :description, :id=>"description" %></p>


    <p><label>Priority:
      <%= select "task", "priority", ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], {:id=>'priority', :name=>"priority"} %>
    </label></p>

    <%= f.submit "Create Item" %>

<% end %>


<%= link_to "Back to  lists", lists_url %>